version: '3.8'

services:

  client:
    container_name: client
    hostname: client
    build:
      context: ./requirements/dockers
      dockerfile: Dockerfile.client
      target: development
    ports:
      - 4200:4200
    restart: unless-stopped
    environment:
      - MODE=production
      - PORT=4200
    working_dir: /
    volumes:
      - ./requirements/dockers/client:/client
    command: ["npm", "run", "start:production"]