version: '3'

services:

  mysql:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: 'matcha_db'
      MYSQL_ROOT_PASSWORD: Motdepasse42DB
    ports: 
      - 3306:3306
    networks:
      - shared-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./requirements/database:/docker-entrypoint-initdb.d
    env_file: ./.env
    
  server:
    container_name: server
    hostname: server
    restart: unless-stopped
    build:
      context: requirements/server/
      target: production
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    networks:
      - shared-network
    depends_on:
      - mysql
    volumes:
      - ./requirements/server:/app
      - /app/node_modules
  
  client:
    container_name: client
    hostname: client
    restart: unless-stopped
    build:
      context: requirements/client/
      target: production
      dockerfile: Dockerfile
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19006:19006
    environment:
      - MODE=production
    networks:
      - shared-network
    depends_on:
      - server
    command: ["yarn", "run", "web"]
    volumes:
      - ./requirements/client:/app
      - /app/node_modules

  phpMyAdmin:
    image: phpmyadmin
    container_name: phpmyadmin
    hostname: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
      # - 443:443 #ssl plus tard
    networks:
      - shared-network
    # network tamere hihihihihihihihihihihihihihihihih

networks:
  shared-network:

volumes:
  mysql-data: