version: '3'

services:

  mysqldb:
    image: mysql:5
    restart: always
    command: --default_authentication_plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'ldermign'
      MYSQL_PASSWORD: 'Motdepasse42'
      MYSQL_ROOT_PASSWORD: Motdepasse42DB
    ports: 
      - 3306:3306
    networks:
      - shared-network
    volumes:
      - mysql-data:/var/lib/mysql
    
  server:
    container_name: server
    restart: unless-stopped
    build:
      context: requirements/server
      target: production
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    networks:
      - shared-network
    depends_on:
      - mysqldb  
  
  client:
    container_name: client
    restart: unless-stopped
    build:
      context: requirements/client
      target: production
      dockerfile: Dockerfile
    ports: 
      - 8080:8081
    networks:
      - shared-network
    depends_on:
      - server

  # phpMyAdmin:
  #   image: phpmyadmin
  #   environment:
  #     PMA_ARBITRARY: 1
  #   ports:
  #     - "8080:80"

networks:
  shared-network:

volumes:
  mysql-data: