version: '3'

services:

  mysqldb:
    image: mysql:5.7.22
    restart: always
    command: --default_authentication_plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'mysql_db_matcha'
      MYSQL_USER: 'ldermign'
      MYSQL_PASSWORD: 'Motdepasse42'
      MYSQL_ROOT_PASSWORD: Motdepasse42DB
    ports: 
      - 3307:3306
    networks:
      - shared-network
    volumes:
      - mysql-data:/var/lib/mysql
    env_file: ./.env
    
  server:
    container_name: server
    hostname: server
    restart: unless-stopped
    build:
      context: requirements/server
      target: production
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    networks:
      - shared-network
    depends_on:
      - mysqldb  
  
  client:
    container_name: client
    hostname: client
    restart: unless-stopped
    build:
      context: requirements/client
      target: production
      dockerfile: Dockerfile
    ports: 
      # - 8080:8081
      - 4200:4200
      - 19000:19000
    environment:
      - MODE=production
      - PORT=4200
    networks:
      - shared-network
    depends_on:
      - server
    command: ["yarn", "run", "web"]

  phpMyAdmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"

networks:
  shared-network:

volumes:
  mysql-data: